name: Npm Test

on:
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-test.yml@main
    with:
      build-command: ${{ env.NPM_BUILD_COMMAND }}
      test-command: ${{ env.NPM_TEST_COMMAND }}
